version: "3"

services:

  redis:
    container_name: redis
    image: redis:7.0.12-alpine

  cut-url:
    container_name: short
    image: aojona/cut-url:latest
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod