spring:
  cache:
    redis:
      time-to-live: 2m     # expiration time in cache, supported units: ns, us, ms, s, m, h, d
  data:
    redis:
      host: localhost
      port: 6379

redis:
  time-to-live: 100         # expiration time in db: must be more 0
  time-unit: days           # unit of expiration time: milliseconds, seconds, minutes, hours or days

strategy:
  encoder: base_62          # encoder: base-62
  token-length: 5           # length of token in short url: must be in range 1..255