server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379

redis:
  time-to-live: 100       # expiration time in Redis: must be more 0
  time-unit: days      # unit of time-to-live: milliseconds, seconds, minutes, hours or days