name: Build, Push And Deploy

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Build App
      run: ./gradle-build.sh

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ github.repository }}:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:

      - name: checkout repo
        uses: actions/checkout@v3
    
      - name: Start services
        run: docker-compose -f docker-compose-prod.yml up -d
